### ISSUE TITLE
BUG - Missing rows in Payment Intent Table

### ISSUE THREAD

**Issue by mvtemple** [fivetran/dbt_stripe_source#14]
**Are you a current Fivetran customer?** 
Yes, Ephemeral Tattoos

**Describe the bug**
Found 5k rows in my raw Payment Intents table that are missing from the staging Payment Intents table

**Steps to reproduce**
```
 select count(*) from raw_data.stripe.payment_intent raw
 left join analytics_data.dbt_meera.stg_stripe__payment_intent stg on raw.id = stg.payment_intent_id
 where stg.payment_intent_id is null

```

**Expected behavior**
I'd expect no missing rows across my raw data and staging data

**Project variables configuration**

```yml
name: ephemeral

profile: ephemeral

version: '1.0'

require-dbt-version: ">=0.14.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  database: false
  identifier: false
  schema: false

models:
  transient: true
  stripe_source: 
    +schema:   # Left blank so that will write to schema "dbt"

on-run-end:
  - "{{ grant_select_on_schemas(schemas, 'reporter') }}"
  - "{{ grant_select_on_schemas(schemas, 'transformer') }}"

config-version: 2

vars:
    # Defined variables for Fivetran Stripe package
    stripe_schema: stripe
    stripe_database: raw_data
    using_invoices:        False  #Disabled since we are not using the invoice and invoice_line_item tables
    using_subscriptions:   False  #Disabled since we are not using the subscription and plan tables.
```

**Package Version**

```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.5
    
  - package: fivetran/stripe_source
    version: 0.3.1

```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [X] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 
Medium-High, on a tight timeline and finding tons of missing rows

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
