### ISSUE TITLE
Multiple Stripe databases

### ISSUE THREAD

**Issue by joshuataylor** [fivetran/dbt_stripe_source#3]
Hi,

I noticed in the docs you only have a single stripe database, is it possible to have multiple Stripe databases? For example to support multicurrency and not be charged transaction fees, you have to have multiple Stripe accounts.

So we have like:
```
stripe_foo
stripe_bar
stripe_baz
```

as our database names.

**Comment by fivetran-kristin** [comment]
Hi @joshuataylor  - Apologies for the delayed response. 

In order to do this, you will first need to union together all the source tables across the multiple databases.

Then, in your `dbt_project.yml` file, add the following variables in order to overwrite the names of the source tables:
```
vars:
  stripe_source:
    balance_transaction: "{{ source('your_stripe_schema', 'unioned_balance_transaction') }}"
    card: "{{ source('your_stripe_schema', 'unioned_card') }}"
    charge: "{{ source('your_stripe_schema', 'unioned_charge') }}"
    customer: "{{ source('your_stripe_schema', 'unioned_customer') }}"
    fee: "{{ source('your_stripe_schema', 'unioned_fee') }}"
    invoice: "{{ source('your_stripe_schema', 'unioned_invoice') }}"
    invoice_line_item: "{{ source('your_stripe_schema', 'unioned_invoice_line_item') }}"
    payment_intent: "{{ source('your_stripe_schema', 'unioned_payment_intent') }}"
    payment_method_card: "{{ source('your_stripe_schema', 'unioned_payment_method_card') }}"
    payment_method: "{{ source('your_stripe_schema', 'unioned_payment_method') }}"
    payout: "{{ source('your_stripe_schema', 'unioned_payout') }}"
    plan: "{{ source('your_stripe_schema', 'unioned_plan') }}"
    refund: "{{ source('your_stripe_schema', 'unioned_refund') }}"
    subscription: "{{ source('your_stripe_schema', 'unioned_subscription') }}"
```

Try this out and let me know if it works.  If it doesn't feel free to reopen the issue, and we're also available for office hours if you want to troubleshoot together.  The link to book that is [here](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours).
