### ISSUE TITLE
[Compatibility] Freshness is a `config` argument in dbt Fusion

### ISSUE THREAD

**Issue by xrpza** [fivetran/dbt_stripe_source#94]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the issue

# Description
In dbt versions <v1.9, `freshness` [is a top-level argument](https://docs.getdbt.com/reference/resource-properties/freshness). Going forward in dbt Fusion v.2.0 (beta) -- [and already optional in dbt v1.9](https://getdbt.slack.com/archives/C088YCAB6GH/p1748530019122049?thread_ts=1748529815.322929&cid=C088YCAB6GH) -- `freshness` will be expected to be placed under the `config` arguments.

![Image](https://github.com/user-attachments/assets/7986d2b9-3a0b-4c8d-bf97-c33fcd550c6b)

Failure to place `freshness` under `config` will result in deprecation warnings like the example below for users looking to leverage dbt Fusion v2.0 (beta).

```console
warning: (soon: error) dbt1060: Ignored unexpected key `"freshness"`. YAML path: `freshness`.
  --> dbt_packages/stripe_source/models/src_stripe.yml:698:9
```

# Challenges
- The current stripe source dbt package supports dbt >= v1.3. Placing freshness under `config` instead of its current locus would likely break compatibility.

# Potential Paths Forward
TBD, but options that immediately come to mind:
- Implementing a breaking change in the existing package that would require users to upgrade to at least dbt v1.9
- Forking the current package to spin-up a new "stripe source fusion" dbt package to support the mechanics of dbt >= v1.9 and dbt Fusion 2.0 (beta)

Wanted to open this issue to get the discussion going around this warning. Also happy to contribute where I can.

### Relevant error log or model output

```shell
warning: (soon: error) dbt1060: Ignored unexpected key `"freshness"`. YAML path: `freshness`.
  --> dbt_packages/stripe_source/models/src_stripe.yml:698:9
```

### Expected behavior

No deprecation warnings related to `freshness` are triggered as a result of using the stripe source package.

### dbt Project configurations

```console
Core:
  - installed: 1.9.5
  - latest:    1.9.5 - Up to date!

Plugins:
  - snowflake: 1.9.4 - Up to date!
```

### Package versions

```yaml
packages:
  - package: dbt-labs/codegen
    version: 0.13.1
    # https://hub.getdbt.com/dbt-labs/codegen/latest/
  - package: dbt-labs/dbt_utils
    version: 1.3.0
    # https://hub.getdbt.com/dbt-labs/dbt_utils/latest/
  - package: fivetran/ad_reporting
    version: [">=1.14.0", "<1.15.0"]
    # https://hub.getdbt.com/fivetran/ad_reporting/latest/
  - package: fivetran/stripe_source
    version:  [">=0.14.2", "<0.15.0"]
    # https://hub.getdbt.com/fivetran/stripe_source/latest/
  - package: godatadriven/dbt_date
    version: [">=0.13.0", "<0.14.0"]
    # https://github.com/godatadriven/dbt-date/tags
```

### What database are you using dbt with?

snowflake

### How are you running this dbt package?

dbt Cloud™

### dbt Version

```console
Core:
  - installed: 1.9.5
  - latest:    1.9.5 - Up to date!

Plugins:
  - snowflake: 1.9.4 - Up to date!
```

### Are you willing to open a PR to help address this issue?

- [x] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.
